name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.2', '8.3' ]
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v3

      - name: Install Redis Tools
        run: sudo apt-get update && sudo apt-get install redis-tools -y

      - name: Check Redis server is running
        run: redis-cli -h localhost -p 6379 ping

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: List installed packages
        run: composer show

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src --level 6

      - name: Check for Vulnerable Dependencies
        run: composer audit

      - name: Run test suite
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: composer test
